### ISSUE TITLE
question : why did you not extend the original fluentvalidation ?

### ISSUE THREAD

**Issue by StefH** [NArnott/fluentvalidation#3]
Your version is out of sync when compared to the original version from https://github.com/JeremySkinner/FluentValidation

Maybe an idea to rewrite your library as an extension on the original, and not a fork ? In that way no duplicate / dll code is used when a project includes your version (because of dependency on system.linq.dynamic and the normal FluentValidation)

**Comment by NArnott** [comment]
This project has no relation to the project you referenced and never did.
